### ISSUE TITLE
How can i redirect my 4G client connection 

### ISSUE THREAD

**Issue by kotik1998** [gr3p1p3/transparent-proxy#15]
Hello, i have a question. I want to know how can i create a proxy of my Andoid 4G connection. How can i use this library to make this happen. Or what i need to make it.

**Comment by gr3p1p3** [comment]
The problem is that your provider does not allow external access from its IP, therefore you need to create your own software to do this.

Basically, your client will use the intermediary server to connect to the instance on your mobile phone. You need:

1. A server to act as an intermediary between your client and your mobile network device.

```javascript
const net = require('net');
const server = new net.createServer();

let firstOne;
let connected = {};
//starting server on port 8080
server.listen(8081,  '0.0.0.0')
    .on('connection', function (socket) {
        if (!firstOne) {
            firstOne = socket; //the first one is your mobile device
        }
        else {
            const id = socket.remoteAddress + ':' + socket.remotePort;
            
            if (!connected[id]) {
                firstOne.on('data', function (data) {
                    socket.write(data);
                });
            }
            connected[id] = true;

            socket.on('data', function (data) {
                firstOne.write(data); //dumping to the first one
            });
        }
    });
```

2. An instance of transparent-proxy with special logic on your Phone (It will work with Termux)

```javascript
const net = require('net');
const ProxyServer = require('transparent-proxy');

const MASTER_PORT = 8081;
const MASTER_SERVER = 'x.x.x.x'; // IP of your server

//init ProxyServer
const server = new ProxyServer();
//starting ProxyServer-Instance on port 8080
server.listen(8080, '0.0.0.0');

const bridgeSocket = new net.Socket();
// connect to main server
bridgeSocket.connect(MASTER_PORT, MASTER_SERVER)
    .on('data', function onRequest(data) {
        const localSocket = new net.Socket();
        localSocket.connect(8080, '0.0.0.0', function onOpenedLocalProxyConnection() {
            localSocket.write(data); //upstream received data
        })
            .on('data', function (_data) {
                bridgeSocket.write(_data);
            });
    });
```


Start the instance on the server and run the code on your mobile first. This absolutely must happen first.
Once this is done you can use your external server as a proxy from any client.

I had implemented a working PoC from which this code was extracted, but I have not tested it now, it is just to give you an idea.

I hope it can help.

**Comment by gr3p1p3** [comment]
@kotik1998 could it help? Can I close this issue? 😀

**Comment by kotik1998** [comment]
yes, i got what i needed. thank you
